lessons/lesson-14/stage1/guide.md, lessons/lesson-14/stage1/list.yaml
=> Fix for YAML list lab (issue #98)

CHANGELOG.md, infrastructure/dns.tf, infrastructure/lb.tf, infrastructure/maintenance_page/index.html, infrastructure/storage.tf, infrastructure/vars.tf, platform/prod/antidote-web.yaml, platform/prod/syringe.yml
Managed to get this done purely through terraform, and using static pages served by a public GCP bucket. Modify `prodstate` in `vars.tf` to set maintenance mode, and re-run `terraform apply`
Closes https://github.com/nre-learning/antidote/issues/139
=> Added maintenance mode

CHANGELOG.md, lessons/lesson-12/syringe.yaml, lessons/lesson-13/syringe.yaml, lessons/lesson-14/syringe.yaml, lessons/lesson-16/syringe.yaml, lessons/lesson-17/syringe.yaml, lessons/lesson-18/syringe.yaml, lessons/lesson-19/syringe.yaml, lessons/lesson-20/syringe.yaml, lessons/lesson-21/syringe.yaml, lessons/lesson-22/syringe.yaml, lessons/lesson-23/syringe.yaml, lessons/lesson-24/syringe.yaml, lessons/lesson-29/syringe.yaml, lessons/lesson-30/syringe.yaml
https://github.com/nre-learning/syringe/pull/41 introduced the ability to serve the lab guide content directly via the Syringe API, so we don't need these URLs anymore.
=> Removed lab guide URL from lesson definitions

CHANGELOG.md, images/vqfx/Dockerfile, images/vqfx/Dockerfile-snap1, images/vqfx/Dockerfile-snap2, images/vqfx/Dockerfile-snap3, images/vqfx/README.md, images/vqfx/launch.sh, images/vqfx/push.sh
https://github.com/nre-learning/antidote/pull/143 switched the lessons over to this new image; this PR introduces the code that makes it work.
It's mostly the same as the old image, but has changes to allow for LLDP. It's also a better name. Keeping both for now for posterity, though `vqfxspeedy` will be deprecated later. Ideally, we can get rid of the three snapshots too, and just have one that we can truly randomize MAC addresses for. However, this will suffice for now.
=> New vqfx image

CHANGELOG.md, docs/contributing/curriculum.rst, lessons/lesson-19/stage1/guide.md, lessons/lesson-19/stage2/guide.md
- Update credentials in REST API lesson, and briefly clarify that internet requests won't work (and why)
- Update docs to explain this further.
Closes https://github.com/nre-learning/antidote/issues/104
=> Clarify internet access restrictions in REST API lesson and docs

CHANGELOG.md, images/githelper/Dockerfile, images/githelper/git-clone.sh, platform/prod/antidote-web.yaml, platform/prod/syringe.yml, platform/ptr/syringe.yml
The lesson directory cloned into lesson endpoints was owned by `root:root`, and so the `antidote` user which is used for user logins couldn't change any of the files with their current permissions.
In addition, this approach caused Syringe to rely on a ConfigMap present in Kubernetes that it didn't control. Instead, this image contains the appropriate cloning logic built-in.
=> Moved to a custom githelper image for making lesson repo available in pods with correct permissions

lessons/lesson-15/stage2/guide.md
While following lesson 15, I noticed that 1 action is executed in the wrong VM(`vqfx1` instead of `st2`) in stage 2
```
cat /antidote/lessons/lesson-15/stage2/vqfx1-config-patch.txt
```
I think this PR will fix that
Great job on this lesson
=> Fix target VM for one action in lesson 15 stage 2

CHANGELOG.md, lessons/lesson-12/syringe.yaml, lessons/lesson-15/syringe.yaml, lessons/lesson-18/syringe.yaml, lessons/lesson-19/syringe.yaml, lessons/lesson-21/syringe.yaml, lessons/lesson-24/syringe.yaml, lessons/lesson-29/syringe.yaml, lessons/lesson-30/syringe.yaml
https://github.com/nre-learning/syringe/pull/88 removed the need to specify a subnet in the connections list. This was never **really** needed - this was here to appease the CNI configuration, but clearly after months of running this, it's obvious that these subnets are not actually enforced - we've been able to use our own addressing on the devices that use these connections.
So, to simplify, we're removing the requirement to specify this in the lesson definition.
=> Removed unneeded subnet declarations from connections list

CHANGELOG.md, lessons/fundamentals/lesson-1-demo/lesson.meta.yaml, lessons/fundamentals/lesson-19-restapis/lesson.meta.yaml, lessons/tools/lesson-12-jsnapy/lesson.meta.yaml, lessons/tools/lesson-13-napalm/lesson.meta.yaml, lessons/tools/lesson-15-stackstorm/lesson.meta.yaml, lessons/tools/lesson-18-todd/lesson.meta.yaml, lessons/tools/lesson-24-pyez/lesson.meta.yaml, lessons/tools/lesson-25-junosjet/lesson.meta.yaml, lessons/tools/lesson-26-openconfig/lesson.meta.yaml, lessons/tools/lesson-29-robot/lesson.meta.yaml, lessons/tools/lesson-30-salt/lesson.meta.yaml, lessons/tools/lesson-31-terraform/lesson.meta.yaml, lessons/workflows/lesson-21-tshoot-ipphone/lesson.meta.yaml, lessons/workflows/lesson-32-stigcompliance/lesson.meta.yaml, lessons/workflows/lesson-33-quickdeviceinventory/lesson.meta.yaml, lessons/workflows/lesson-34-configbackup/lesson.meta.yaml, lessons/workflows/lesson-35-devicespecifictemplate/lesson.meta.yaml
This PR removes all tags from lesson definitions to be compatible with Syringe changes introduced in https://github.com/nre-learning/syringe/pull/123.
To minimize the impact of this change, we have pushed a new tag for the existing images (i.e. `antidotelabs/vqfx:snap1`) at the exact same image ID, but to an image name that doesn't rely on tags for differentiation. So, instead of:
- `antidotelabs/vqfx:snap1`
- `antidotelabs/vqfx:snap2`
- `antidotelabs/vqfx:snap3`
We have:
- `antidotelabs/vqfx-snap1`
- `antidotelabs/vqfx-snap2`
- `antidotelabs/vqfx-snap3`
These images are cryptographically identical to their tagged counterpart, but without the tag, we can now inject the appropriate version at the Syringe level per the new behavior. Both `latest` and `v0.4.0` versions of these images have …
=> Removing tags from curriculum

CHANGELOG.md, collections/ntc/collection.meta.yaml, collections/packetpushers/collection.meta.yaml, collections/twinbridges/collection.meta.yaml
Most of the collections currently in place are there as a PoC. We've talked to a lot of companies about getting involve with NRE Labs, so we create their company as a collection to show them what it might look like.
Since we're nearing the next release, I thought it valuable to promote a small portion of them to `prod` status so that they'll show in the UI when we move to the next release in the next few days.
Collections were initially thought of as a way to organize content, but it also serves as a useful way to link to external resources for "next steps". Naturally, Network to Code and Twin Bridges come to mind, as they specialize in network automation training. So, I included them in this batch as well. Packet Pushers, while they don't specialize in it like the other two companies, …
=> Promoting initial batch of collections

CHANGELOG.md, images/utility/Dockerfile, images/utility/push.sh, images/utility/requirements.txt, lessons/fundamentals/lesson-14-yaml/stage2/guide.md, lessons/fundamentals/lesson-17-git/stage1/guide.md, lessons/tools/lesson-13-napalm/stage1/notebook.ipynb, lessons/tools/lesson-13-napalm/stage2/notebook.ipynb, lessons/tools/lesson-13-napalm/stage4/notebook.ipynb
No major changes - just minor fixes that were raised in testing, and are easy and low-impact to fix.
- Installing correct version of python deps in utility image
- Removed section at the top of NAPALM jupyter notebooks that point to erroneous link. This link is provided, correctly, as part of the platform now, so this whole section is not needed.
- Added steps in Git lesson to add identity, so the commit works.
- Installing jsnapy manually by commit ID in utility image, to get the YAML fix.
- Adjust guide for stage 2 of the YAML lesson so that the last snippet uses `<pre>` tags, to fix the need to hit enter to get the code to execute.
=> Final Fixes for v1.0.0

CHANGELOG.md, images/asterisk/Makefile, images/container-vqfx/build.sh, images/cvx/Makefile, images/netbox/Makefile, images/pjsua-lindsey/Makefile, images/salt/Makefile, images/selfservice-flask-app/Makefile, images/st2/Makefile, images/terraform/Makefile, images/utility/Makefile
The nightly build is up and running but because Docker uses cached images by default for any unchanged Dockerfile actions, any upstream fixes don't have any impact. For instance @cloudtoad fixed an issue in the [upstream napalm pack](https://github.com/nre-learning/stackstorm-napalm/pull/2) for our stackstorm image which is pulled by this Dockerfile, but since the line in the Dockerfile hasn't changed, it continues to use the cached image without the fix.
Going forward each image's Makefile will ignore the cache and build each image from scratch, to ensure the latest updates in all aspects of the build specification.
=> Disable caching for image builds

collections/juniper/collection.meta.yaml
Rather than link to the main website, it's probably more useful to link directly to training resources where folks can continue their learning journey.
=> Update Juniper collection with link to training

CHANGELOG.md, images/frr/Dockerfile, images/frr/Makefile, images/frr/launch.sh, lessons/fundamentals/lesson-98-frr/lesson.meta.yaml, lessons/fundamentals/lesson-98-frr/stage1/configs/branch-1.py, lessons/fundamentals/lesson-98-frr/stage1/configs/branch-1/bgpd.conf, lessons/fundamentals/lesson-98-frr/stage1/configs/branch-1/daemons, lessons/fundamentals/lesson-98-frr/stage1/configs/branch-1/interfaces, lessons/fundamentals/lesson-98-frr/stage1/configs/branch-1/vtysh.conf, lessons/fundamentals/lesson-98-frr/stage1/configs/branch-1/zebra.conf, lessons/fundamentals/lesson-98-frr/stage1/configs/branch-2.py, lessons/fundamentals/lesson-98-frr/stage1/configs/branch-2/bgpd.conf, lessons/fundamentals/lesson-98-frr/stage1/configs/branch-2/daemons, lessons/fundamentals/lesson-98-frr/stage1/configs/branch-2/frr.conf, lessons/fundamentals/lesson-98-frr/stage1/configs/branch-2/interfaces, lessons/fundamentals/lesson-98-frr/stage1/configs/branch-2/vtysh.conf, lessons/fundamentals/lesson-98-frr/stage1/configs/branch-2/zebra.conf, lessons/fundamentals/lesson-98-frr/stage1/configs/hub.py, lessons/fundamentals/lesson-98-frr/stage1/configs/hub/bgpd.conf, lessons/fundamentals/lesson-98-frr/stage1/configs/hub/daemons, lessons/fundamentals/lesson-98-frr/stage1/configs/hub/frr.conf, lessons/fundamentals/lesson-98-frr/stage1/configs/hub/interfaces, lessons/fundamentals/lesson-98-frr/stage1/configs/hub/vtysh.conf, lessons/fundamentals/lesson-98-frr/stage1/configs/hub/zebra.conf, lessons/fundamentals/lesson-98-frr/stage1/configs/lessontools.py, lessons/fundamentals/lesson-98-frr/stage1/guide.md
Create FRR image w/netconf support for use in NRELabs.
Nearly complete, need to finish testing the python configuration bits.
Closes #264
=> FRR image and PoC lesson

CHANGELOG.md, images/asterisk/Dockerfile, images/netbox/Dockerfile, images/pjsua-lindsey/Dockerfile
The CentOS base images were updated with the release of CentOS 8, and the images that were built to use this didn't specify tag, and are not compatible with 8 (currently breaking in nightly builds). Setting statically to 7 for now. We can, of course, circle back in the future and fix the incompatibility and use 8 if needed.
=> Set tshoot lesson images to use centos7

CHANGELOG.md, images/kali/Dockerfile
The wordlist package is needed by `wpscan` for the lesson we're building to use this image, and the default Kali Docker image doesn't include it.
@94halldah - please review.
=> Add wordlist package to Kali image

CHANGELOG.md, images/st2/Dockerfile
As discussed in https://github.com/nre-learning/nrelabs-curriculum/issues/280, this PR temporarily downgrades netmiko to 2.4.2 to get things working again quickly enough, since the st2 image doesn't yet support the py3 version required for the latest netmiko.
https://github.com/nre-learning/nrelabs-curriculum/issues/294 will provide a longer-term solution for this by upgrading python and stackstorm, and will be implemented in a future (hopefully the next) release.
Closes #280
=> Temporarily pin netmiko to 2.4.2 in st2 image

CHANGELOG.md, lessons/workflows/lesson-21-tshoot-ipphone/lesson.meta.yaml, lessons/workflows/lesson-21-tshoot-ipphone/stage1/guide.md
Making some mostly cosmetic changes to the troubleshooting lesson. For now, we can disable the netbox endpoint, as it's not currently used. I left it in, commented-out. Also, `vqfx3` isn't needed, so we can remove it from the lesson.
The other changes are almost purely aesthetic. I did also add a second `cd` command to ensure that both the `sipphone` and `linux` endpoints start in the right directory before executing their commands.
Closes #263
=> Cleaning up Troubleshooting Lesson

lessons/fundamentals/lesson-17-git/stage1/guide.md
As spotted by @Mierdin in the first Labs & Latte episode, the show command is useless in that summary
=> (git lesson) Remove command "show" from 1st stage summary

CHANGELOG.md, lessons/tools/lesson-41-ansible-network/stage4/configs/vqfx1.txt
In response to a report raised in https://discuss.nrelabs.io/t/ospf-lab-stage-4-on-ansible/244/2
/cc @IPvSean - looks like the updated IP address was just placed on the wrong interface. Easy to fix.
=> Fix config for stage4 vqfx1 config in ansible lesson

images/gnmic/Dockerfile, images/gnmic/Makefile, images/gnmic/image.meta.yaml
This image is a first step in adding `gnmic` lesson to nre.labs as per #339 
It adds the relevant endpoint images based off of `antidote/utility` image.
=> added gnmic endpoint image

CHANGELOG.md, lessons/ansible-network-automation/stage0/hosts, lessons/ansible-network-automation/stage3/ansible.cfg, lessons/ansible-network-automation/stage3/configs/vqfx1-junos.txt
This fixes some long-standing issues in the Ansible lesson.
/cc @IPvSean 
This has been a [known problem for some time](https://github.com/nre-learning/nrelabs-curriculum/issues/304). At the time the only known solution was coming in this PR: https://github.com/ansible/ansible/pull/68184
However, as of today it's still not merged, and unclear if it would actually fix the problem. On a whim I did some additional googling and found [this SO post](https://stackoverflow.com/questions/49629480/ansible-fails-to-connect-with-ssh-banner-exchange), which mentions this could be caused by using the wrong ansible credential parameters. I changed this and it **immediately** and consistently fixed the problem. So this PR includes that fix.
Closes …
=> Fix connectivity issues in Ansible lesson

.github/workflows/main.yml, images/ansible/image.meta.yaml, images/asterisk/image.meta.yaml, images/crpd/image.meta.yaml, images/cvx/image.meta.yaml, images/gitea/image.meta.yaml, images/gnmic/image.meta.yaml, images/pjsua-lindsey/image.meta.yaml, images/salt/image.meta.yaml, images/stackstorm/image.meta.yaml, images/terraform/image.meta.yaml, images/utility/image.meta.yaml, images/vqfx-snap1/image.meta.yaml, images/vqfx-snap2/image.meta.yaml, images/vqfx-snap3/image.meta.yaml
This is an update to bring the curriculum into compatibility with the changes in https://github.com/nre-learning/antidote-core/pull/214
The `networkInterfaces` field is now optional, and not necessary for any of the existing images to include.
=> Updated images to not include networkInterfaces field by default
